# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "CJeon's Blog"
email: "adobecs5.kaist@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  개발 개발
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cjeon.github.io" # the base hostname & protocol for your site
twitter_username: time_rb
github_username:  CJeon

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
exclude: [vendor]
paginate: 5
paginate_path: "/blog/page:num/"
gems:
  - jekyll-sitemap
